### ISSUE TITLE
Spec Failures Of Unusual Origin (SFOUO's)

### ISSUE THREAD

**Issue by jfelchner** [DatabaseCleaner/database_cleaner#215]
When attempting to implement #212, I wanted to make sure (obviously) that I hadn't broken anything.  I attempted to get the test suite to run and after some trial and error, got all but 3 to pass.  The last 3 are all the same error and have me perplexed.  Here is the stacktrace:

```
  3) DatabaseCleaner::Moped::Truncation when collections are provided to the :except option truncates all but the specified collections
     Failure/Error: MopedTest::Widget.new({:name => 'some widget'}.merge(attrs)).save!
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/protocol/reply.rb:70:in `command_failure?'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:73:in `block in command'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:564:in `[]'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:564:in `block (3 levels) in flush'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:563:in `map'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:563:in `block (2 levels) in flush'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:129:in `ensure_connected'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:559:in `block in flush'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:574:in `logging'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:558:in `flush'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:547:in `process'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:71:in `command'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/node.rb:400:in `refresh'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/cluster.rb:168:in `block in refresh'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/cluster.rb:181:in `each'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/cluster.rb:181:in `refresh'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/cluster.rb:134:in `nodes'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/cluster.rb:202:in `with_primary'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/session/context.rb:108:in `with_node'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/session/context.rb:56:in `insert'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/collection.rb:91:in `block in insert'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/session.rb:312:in `with'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/moped-1.3.2/lib/moped/collection.rb:90:in `insert'
     # ./spec/database_cleaner/moped/moped_examples.rb:18:in `save!'
     # ./spec/database_cleaner/moped/truncation_spec.rb:35:in `create_widget'
     # ./spec/database_cleaner/moped/truncation_spec.rb:64:in `block (3 levels) in <module:Moped>'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `instance_eval'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `block in run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:111:in `run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:388:in `block in run_examples'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `map'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `run_examples'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:369:in `run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `block in run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `map'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:370:in `run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `map'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `block in run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/reporter.rb:34:in `report'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:25:in `run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
     # /opt/boxen/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `block in autorun'
```

I get this error on the following 3 specs:

```
rspec ./spec/database_cleaner/moped/truncation_spec.rb:42 # DatabaseCleaner::Moped::Truncation truncates all collections by default
rspec ./spec/database_cleaner/moped/truncation_spec.rb:52 # DatabaseCleaner::Moped::Truncation when collections are provided to the :only option only truncates the specified collections
rspec ./spec/database_cleaner/moped/truncation_spec.rb:63 # DatabaseCleaner::Moped::Truncation when collections are provided to the :except option truncates all but the specified collections
```

Any thoughts?

**Comment by etagwerker** [comment]
@jfelchner Sorry for the delay. Travis has been configured and the build now passes. Please let me know if you still find an unusual failure.
