### ISSUE TITLE
AR test cases fails against AR 4.0

### ISSUE THREAD

**Issue by voxik** [DatabaseCleaner/database_cleaner#237]
```
 1) DatabaseCleaner::ActiveRecord::Transaction#start using begin_transaction should increment open transactions if possible
     Failure/Error: connection.should_receive(:increment_open_transactions)
       (Mock "connection").increment_open_transactions(any args)
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/database_cleaner/active_record/transaction_spec.rb:25:in `block (5 levels) in <module:ActiveRecord>'
  2) DatabaseCleaner::ActiveRecord::Transaction#start using begin_transaction should tell ActiveRecord to increment connection if its not possible to increment current connection
     Failure/Error: ::ActiveRecord::Base.should_receive(:increment_open_transactions)
       (<ActiveRecord::Base (class)>).increment_open_transactions(any args)
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/database_cleaner/active_record/transaction_spec.rb:31:in `block (5 levels) in <module:ActiveRecord>'
  3) DatabaseCleaner::ActiveRecord::Transaction#start using begin_db_transaction should increment open transactions if possible
     Failure/Error: connection.should_receive(:increment_open_transactions)
       (Mock "connection").increment_open_transactions(any args)
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/database_cleaner/active_record/transaction_spec.rb:25:in `block (5 levels) in <module:ActiveRecord>'
  4) DatabaseCleaner::ActiveRecord::Transaction#start using begin_db_transaction should tell ActiveRecord to increment connection if its not possible to increment current connection
     Failure/Error: ::ActiveRecord::Base.should_receive(:increment_open_transactions)
       (<ActiveRecord::Base (class)>).increment_open_transactions(any args)
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/database_cleaner/active_record/transaction_spec.rb:31:in `block (5 levels) in <module:ActiveRecord>'
  5) DatabaseCleaner::ActiveRecord::Transaction#clean manual accounting of transaction count should decrement open transactions if possible
     Failure/Error: connection.should_receive(:decrement_open_transactions)
       (Mock "connection").decrement_open_transactions(any args)
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/database_cleaner/active_record/transaction_spec.rb:65:in `block (4 levels) in <module:ActiveRecord>'
  6) DatabaseCleaner::ActiveRecord::Transaction#clean manual accounting of transaction count should decrement connection via ActiveRecord::Base if connection won't
     Failure/Error: ::ActiveRecord::Base.should_receive(:decrement_open_transactions)
       (<ActiveRecord::Base (class)>).decrement_open_transactions(any args)
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/database_cleaner/active_record/transaction_spec.rb:82:in `block (4 levels) in <module:ActiveRecord>'
```

It seems that https://github.com/bmabey/database_cleaner/issues/150 was incomplete.

**Comment by voxik** [comment]
I still observe this issue with database_cleaner 1.4.1

**Comment by voxik** [comment]
Still an issue for 1.5.3

**Comment by voxik** [comment]
Still an issue for 1.6.1
