### ISSUE TITLE
Broken on Padrino + ActiveRecord.

### ISSUE THREAD

**Issue by graudeejs** [DatabaseCleaner/database_cleaner#243]
I've had weird things happening.
I was experimenting with Padrino framework Padrino + Sequel + rspec + sqlite3. Tests worked.

Then I dumped sequel and switched to ActiveRecord.
Everything was fine until I started writing/running tests.

I got this error
```
/home/graudeejs/.rvm/rubies/ruby-2.0.0-p247/bin/ruby -S rspec ./spec/models/user_spec.rb

Finished in 0.03415 seconds
0 examples, 0 failures
/home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/active_record/truncation.rb:123:in `db_version': undefined local variable or method `postgresql_version' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x0000080717cb18> (NameError)
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/active_record/truncation.rb:131:in `restart_identity'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/active_record/truncation.rb:140:in `truncate_tables'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/active_record/truncation.rb:234:in `block in clean'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:168:in `disable_referential_integrity'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/active_record/truncation.rb:230:in `clean'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/base.rb:40:in `clean_with'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/configuration.rb:85:in `block in clean_with'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/configuration.rb:85:in `each'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/database_cleaner-1.1.1/lib/database_cleaner/configuration.rb:85:in `clean_with'
	from /home/graudeejs/src/ruby/graudeejs/spec/spec_helper.rb:31:in `block (2 levels) in <top (required)>'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:21:in `instance_eval'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:21:in `run'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:85:in `block in run'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:85:in `each'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:85:in `run'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:446:in `run_hook'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:27:in `block in run'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/reporter.rb:58:in `report'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:25:in `run'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:80:in `run'
	from /home/graudeejs/.rvm/gems/ruby-2.0.0-p247@graudeejs/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:17:in `block in autorun'
Coverage report generated for RSpec to /home/graudeejs/src/ruby/graudeejs/coverage. 28 / 38 LOC (73.68%) covered.
/home/graudeejs/.rvm/rubies/ruby-2.0.0-p247/bin/ruby -S rspec ./spec/models/user_spec.rb failed
```

I don't use PostgreSQL, so something is obviously wrong.
I started downgrading database_cleaner and v1.0.1 was the last release that works.

There's database_cleaner related content of spec/spec_helper.rb
```
  # # config.use_transactional_fixtures = false
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end
  config.before(:each) do
    DatabaseCleaner.start
  end
  config.after(:each) do
    DatabaseCleaner.clean
  end
```
As you can see nothing special.

**Comment by etagwerker** [comment]
@graudeejs I believe that this is no longer an issue. You can see a sample app over here: https://github.com/etagwerker/clean-padrino

Please let me know if this is still happening and I'll reopen the issue.
