### ISSUE TITLE
The 'truncation' strategy does not exist [...] Available strategies: truncation

### ISSUE THREAD

**Issue by ekampp** [DatabaseCleaner/database_cleaner#299]
Hi everybody. As the title suggests there seems to be a bit of a missmatch in the way that mongoid strategies are determined in the current master. 

This is the full error message ([which is raised from here](https://github.com/DatabaseCleaner/database_cleaner/blob/master/lib/database_cleaner/base.rb#L137)): 

```
The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation
```

And as you can see, "truncation" appears on the list of available strategies. I tried assigning the strategy as a string and a symbol, but both resulted in this problem.

Any suggestions, or is this a bug?

**Comment by TimMoore** [comment]
I'm also getting this error in my app after updating from database_cleaner 1.3.0 to 1.4.0.

The backtrace is:

```
/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:139:in `rescue in orm_strategy': The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation (DatabaseCleaner::UnknownStrategySpecified)
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:135:in `orm_strategy'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:33:in `create_strategy'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:57:in `strategy='
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:157:in `set_default_orm_strategy'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:11:in `initialize'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:46:in `new'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:46:in `connections'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:91:in `clean_with'
	from /Users/tmoore/Projects/cultureamp/murmur/spec/rails_helper.rb:76:in `block in <top (required)>'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/spork-0.9.2/lib/spork.rb:37:in `each_run'
	from /Users/tmoore/Projects/cultureamp/murmur/spec/rails_helper.rb:74:in `<top (required)>'
	from /Users/tmoore/Projects/cultureamp/murmur/spec/controllers/account_controller_spec.rb:1:in `require'
	from /Users/tmoore/Projects/cultureamp/murmur/spec/controllers/account_controller_spec.rb:1:in `<top (required)>'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:66:in `rescue in run'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:62:in `run'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/exe/rspec:4:in `<main>'
```

and the code invoking DatabaseCleaner is:

```ruby
DatabaseCleaner.clean_with :truncation
```

**Comment by TimMoore** [comment]
It looks like this is in turned caused by a (swallowed) load error when requiring `database_cleaner/mongoid/truncation.rb`:

```
[5] pry(#<DatabaseCleaner::Base>)> exception
=> #<LoadError: cannot load such file -- mongoid/tree>
[6] pry(#<DatabaseCleaner::Base>)> exception.backtrace
=> ["/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/mongoid/truncation.rb:5:in `<top (required)>'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:135:in `orm_strategy'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:33:in `create_strategy'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:57:in `strategy='",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:157:in `set_default_orm_strategy'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:11:in `initialize'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:46:in `new'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:46:in `connections'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:91:in `clean_with'",
 "/Users/tmoore/Projects/cultureamp/murmur/spec/rails_helper.rb:77:in `block in <top (required)>'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/spork-0.9.2/lib/spork.rb:37:in `each_run'",
 "/Users/tmoore/Projects/cultureamp/murmur/spec/rails_helper.rb:74:in `<top (required)>'",
 "/Users/tmoore/Projects/cultureamp/murmur/spec/controllers/account_controller_spec.rb:1:in `require'",
 "/Users/tmoore/Projects/cultureamp/murmur/spec/controllers/account_controller_spec.rb:1:in `<top (required)>'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:66:in `rescue in run'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:62:in `run'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'",
 "/Users/tmoore/Projects/cultureamp/murmur/.gem/ruby/2.1.5/gems/rspec-core-3.1.7/exe/rspec:4:in `<main>'"]
```

Looks like that snuck in (accidentally?) in commit 61feda02e0999a684951f2afb6746fd2ddf814f4. We're still on Mongoid 3.1.6, and that `mongoid/tree` file is not present in that version.

**Comment by TimMoore** [comment]
Hmm... `mongoid/tree` isn't in Mongoid master either... seems to be a [separate gem](https://github.com/benedikt/mongoid-tree). Typo?

**Comment by dbackeus** [comment]
+1

Get the same error with the following in spec_helper.rb:

```ruby

  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
```

**Comment by lucke84** [comment]
+1

After upgrading from 1.3.0 to 1.4.0:

```
/home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:139:in `rescue in orm_strategy': The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation (DatabaseCleaner::UnknownStrategySpecified)
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:135:in `orm_strategy'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:33:in `create_strategy'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:57:in `strategy='
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:157:in `set_default_orm_strategy'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:11:in `initialize'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:29:in `new'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:29:in `add_cleaner'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/database_cleaner-1.4.0/lib/database_cleaner/configuration.rb:23:in `[]'
	from /home/luca/myproject/spec/spec_helper.rb:52:in `block (2 levels) in <top (required)>'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/hooks.rb:21:in `run'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/hooks.rb:85:in `block in run'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/hooks.rb:85:in `each'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/hooks.rb:85:in `run'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/hooks.rb:446:in `run_hook'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:23:in `block in run'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/reporter.rb:58:in `report'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:21:in `run'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
	from /home/luca/.rvm/gems/ruby-2.2.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by balauru** [comment]
Same issue here.

My config file is:

```
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner[:mongoid].strategy = :truncation
    DatabaseCleaner.clean_with(:truncation)
  end

  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end
end
```

Error stack is:

```
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner[:mongoid].strategy = :truncation
    DatabaseCleaner.clean_with(:truncation)
  end

  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end
end
```

**Comment by celsoMartins** [comment]
The same here, with Sinatra. My spec_helper

require 'rspec'
require 'rack/test'
require 'simplecov'
require 'database_cleaner'
require 'json_spec'

require File.dirname(__FILE__) + '/../application'

SimpleCov.start

Sinatra::Base.set :environment, :test
Sinatra::Base.set :run, false
Sinatra::Base.set :raise_errors, true
Sinatra::Base.set :show_exceptions, true
Sinatra::Base.set :logging, false

RSpec.configure do |conf|
  conf.include Rack::Test::Methods
  conf.before(:suite) do
    GC.disable
    DatabaseCleaner.orm = :mongoid
    DatabaseCleaner.strategy = :truncation
  end

  conf.before(:each) do
    DatabaseCleaner.start
  end

  conf.after(:each) do
    DatabaseCleaner.clean
  end
end

def app
  Application
end

**Comment by raphaelcm** [comment]
Has a new gem been released with this fix?

**Comment by shingara** [comment]
:+1: to new gem release

**Comment by Elyasin** [comment]
:+1:  to new gem release

**Comment by doofdoofsf** [comment]
:+1: to the gem release

**Comment by AntonTrapp** [comment]
:+1: to the gem release

**Comment by robertomiranda** [comment]
Downgrading to '1.3.0' works for me

**Comment by PWKad** [comment]
Same - 
`  gem 'database_cleaner', '~> 1.3.0'`
Fixed error

**Comment by lucke84** [comment]
Going back to `1.3.0` does fix the issue, it makes sense though to release a new version of the gem, should not be a big deal :)

**Comment by raphaelcm** [comment]
Who's the maintainer of this Gem? Any word on when we can expect a new version?

**Comment by etagwerker** [comment]
@raphaelcm I'm one of the maintainers. I will release a new version soon. 

In the mean time, could you confirm that it's working fine using `master`?

**Comment by raphaelcm** [comment]
Confirmed with:

```
GIT
  remote: https://github.com/DatabaseCleaner/database_cleaner.git
  revision: bceb09bc8721595db6905966084d03015c8b3725
  specs:
    database_cleaner (1.4.0)
```

Using `rspec (3.2.0)` and `mongoid (3.1.6)`

**Comment by fbernier** [comment]
I confirm master is working as expected.

**Comment by TangMonk** [comment]
I rollback to 1.3.0, worked.

**Comment by etagwerker** [comment]
@fbernier Great! So it should be working on `1.4.1` (released yesterday)

**Comment by AntonTrapp** [comment]
1.4.1 working for me. TNX!

**Comment by lucke84** [comment]
1.4.1 works for me too. Thanks!

**Comment by adrianotadao** [comment]
1.4.1 works well. Thanks a lot

**Comment by hackeron** [comment]
Seems to be back with 1.5.0 :(

```
/usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:139:in `rescue in orm_strategy': The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation (DatabaseCleaner::UnknownStrategySpecified)
	from /usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:135:in `orm_strategy'
	from /usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:33:in `create_strategy'
	from /usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:57:in `strategy='
	from /usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:157:in `set_default_orm_strategy'
	from /usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:11:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:29:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:29:in `add_cleaner'
	from /usr/local/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:23:in `[]'
	from /Users/Hackeron/Development/Xanview/timeline/spec/spec_helper.rb:64:in `block (2 levels) in <top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:357:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in `block in run_hooks_with'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in `run_hooks_with'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1626:in `with_suite_hooks'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
	from /usr/local/bin/rspec:23:in `load'
	from /usr/local/bin/rspec:23:in `<main>'
```

**Comment by pezholio** [comment]
Yup, same here :disappointed: 

Relevant Travis build here:

https://travis-ci.org/theodi/panopticon/builds/78329424#L319

I've pinned to 1.4.1 for now

**Comment by hugocorbucci** [comment]
And same here

**Comment by hugocorbucci** [comment]
The previous workaround (including mongoid-tree in Gemfile) no longer works. So this is likely a new somewhat unrelated issue.

**Comment by reiz** [comment]
I'm getting the same error with 1.5.0. :-(

**Comment by hackeron** [comment]
As a temporary solution add this to your gemfile:

```ruby
gem 'database_cleaner', git: 'https://github.com/DatabaseCleaner/database_cleaner.git'
```

**Comment by alexfarrill** [comment]
Same error with 1.5.0

**Comment by etagwerker** [comment]
@alexfarrill Have you tried @hackeron's suggestion?

**Comment by alexfarrill** [comment]
That works, thanks!

**Comment by magedmakled** [comment]
Start working version 1.5.1

**Comment by hugocorbucci** [comment]
+1

Hugo Corbucci
Skype user: hugo.corbucci
Twitter: hugocorbucci

**Comment by igordcsouza** [comment]
This work for me! 
gem 'database_cleaner', git: 'https://github.com/DatabaseCleaner/database_cleaner.git'

**Comment by vinagrito** [comment]
I wouldn't encourage to use the master version (in general) if you have a good version. Stick to a know working version. As @magedmakled mentioned, works on `1.5.1`. I see `1.5.3` working as well
