### ISSUE TITLE
UnknownStrategySpecified: The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation

### ISSUE THREAD

**Issue by mrmylanman** [DatabaseCleaner/database_cleaner#322]
Hello,

Thanks for this gem, I have used it a lot in Rails and am a big fan. I recently started a project that is somewhat simple so I decided using Grape as a standalone might be best, so I set it up and then worked on configuring rspec.

My `spec_helper.rb` file looks like this:

```ruby
require 'rubygems'

ENV['RACK_ENV'] ||= 'test'

require 'rack/test'

require File.expand_path('../../config/environment', __FILE__)

RSpec.configure do |config|

  config.before :each do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.start
  end

  config.after do
    DatabaseCleaner.clean
  end
  
end
```

When I run rspec, I get the following error:

```ruby
API::Models::User

  An error occurred in an after hook
    DatabaseCleaner::UnknownStrategySpecified: The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation
    occurred at /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:139:in `rescue in orm_strategy'

  example at ./spec/models/user_spec.rb:19 (FAILED - 1)

Failures:

  1) API::Models::User 
     Failure/Error: Unable to find matching line from backtrace
     DatabaseCleaner::UnknownStrategySpecified:
       The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation
     # ./spec/spec_helper.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.00365 seconds (files took 0.72737 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/user_spec.rb:19 # API::Models::User 
```

I have also tried just leaving the strategy out, but it doesn't seem to make a difference.

The `database_cleaner` gem is version 1.4.0 and the Mongoid gem is version '4.0.0'. I am not 100% sure what other information would be useful, but I can certainly provide more if needed.

**Comment by tagliala** [comment]
It should be a duplicate of #299

**Comment by mrmylanman** [comment]
Thanks, I'll look into that issue.

**Comment by tagliala** [comment]
You're welcome, I'm experiencing the same issue :)
