### ISSUE TITLE
NoORMDetected

### ISSUE THREAD

**Issue by kiddrew** [DatabaseCleaner/database_cleaner#325]
I have a clean install of database_cleaner 1.4.0 on Rspec 3.1.0 with Capybara 2.4.4 and I'm getting the following error:

    /Users/andrew/.rvm/gems/ruby-2.1.1/bundler/gems/database_cleaner-1b2eda6615f5/lib/database_cleaner/base.rb:149:in `autodetect': No known ORM was detected!  Is ActiveRecord, DataMapper, Sequel, MongoMapper, Mongoid, Moped, or CouchPotato, Redis or Ohm loaded? (DatabaseCleaner::NoORMDetected)

My rails_helper.rb is this:

```ruby
    ENV["RAILS_ENV"] ||= 'test'
    require File.expand_path("../../config/environment", __FILE__)
    require 'rspec/rails'
    require 'capybara/rspec'
    require 'capybara/rails'
    require 'database_cleaner'
    require 'pp'
    require 'devise'
    require 'factory_girl_rails'
    
    Dir[Rails.root.join("spec/support/**/*.rb")].each { |f| require f }
    
    ActiveRecord::Migration.maintain_test_schema!
    
    RSpec.configure do |config|
      config.include Rails.application.routes.url_helpers
    
      config.fixture_path = "#{::Rails.root}/spec/fixtures"
    
      config.order = :random
    
      config.include Capybara::DSL
    
      config.include(MailerMacros)
      config.before(:each) { reset_email }
    
      config.include FactoryGirl::Syntax::Methods
    
      config.include Warden::Test::Helpers
      Warden.test_mode!
    
      config.use_transactional_fixtures = true
    
      config.expect_with :rspec do |c|
        c.syntax = [:should, :expect]
      end
    
      config.before(:suite) do
        DatabaseCleaner.strategy = :transaction
        DatabaseCleaner.clean_with(:truncation)
      end
    
      config.around(:each) do |example|
        DatabaseCleaner.cleaning do
          example.run
        end
      end
    
      config.infer_spec_type_from_file_location!
    end
```

I've never had this issue before and I'm finding no help from Google.  Help?

**Comment by vrinek** [comment]
@kiddrew, which version of Rails are you using? Could you also paste your Gemfile.lock here (if possible)?

**Comment by kiddrew** [comment]
Hi @vrinek.  I unfortunately don't have my environment in the state it was in when I saw that issue, and I have somehow fixed it.  I wish I knew exactly what I did.  =)

I'll close for now and reopen if I see the issue again.

**Comment by michaelachrisco** [comment]
I have an update on this issue:
```
/Users/mike/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:149:in `autodetect': No known ORM was detected!  Is ActiveRecord, DataMapper, Sequel, MongoMapper, Mongoid, Moped, or CouchPotato, Redis or Ohm loaded? (DatabaseCleaner::NoORMDetected)
```

My spec_helper.rb looks like:
```Ruby
require 'database_cleaner'

RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.start
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :transaction
  end

  config.before(:each, :js => true) do
    DatabaseCleaner.strategy = :truncation
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end
end
```

This error only occurs if you have no tests in rspec: 
```
$ rspec
No examples found.


Finished in 0.00034 seconds (files took 0.08692 seconds to load)
0 examples, 0 failures

/Users/mike/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:149:in `autodetect': No known ORM was detected!  Is ActiveRecord, DataMapper, Sequel, MongoMapper, Mongoid, Moped, or CouchPotato, Redis or Ohm loaded? (DatabaseCleaner::NoORMDetected)
	from /Users/mike/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:6:in `initialize'
```

One or more tests:

```Ruby
require 'rails_helper'

RSpec.describe 'home/index.html.erb', :type => :view do
  pending "add some examples to (or delete) #{__FILE__}"
end
```

Then:
```Bash
$ rspec
*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) home/index.html.erb add some examples to (or delete) /Users/michaelchrisco/dev/development/hay_app/spec/views/home/index.html.erb_spec.rb
     # Not yet implemented
     # ./spec/views/home/index.html.erb_spec.rb:4


Finished in 0.07379 seconds (files took 2.16 seconds to load)
1 example, 0 failures, 1 pending
```

Just wanted to leave this here in case anyone else is getting this error.

**Comment by prashanthsams** [comment]
Facing similar issue :( I don't think this is the fix
> /Users/prashanth_sams/.rvm/gems/ruby-2.0.0-p598/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:147:in `autodetect': No known ORM was detected!  Is ActiveRecord, DataMapper, Sequel, MongoMapper, Mongoid, Moped, or CouchPotato, Redis or Ohm loaded? (DatabaseCleaner::NoORMDetected)

**Comment by etagwerker** [comment]
@prashanthsams Could you paste your code here? Also, what ORM are you using? Have you tried with 1.4.1 or `master`?

**Comment by raj-kasi** [comment]
Facing the same issue; Can any one help on this? 

Code is here: http://stackoverflow.com/questions/30168421/autodetect-no-known-orm-was-detected

**Comment by sobinsunny** [comment]
I faced this problem and  I fixed this issue by adding  ```require 'rails_helper'``` in ```spec_helper.rb``` file

**Comment by alex198211** [comment]
I could be wrong but I think there's no need to load the rails helper for all examples...like I am facing now the same error all out of the sudden for some unit tests..

**Comment by muneebaahmad** [comment]
For me, this usually shows up when I have a syntax error in the file.
