### ISSUE TITLE
Failed test on master 

### ISSUE THREAD

**Issue by tranvictor** [DatabaseCleaner/database_cleaner#341]
```ruby
1) schema_migrations table is not truncated
     Failure/Error: active_record_gp_migrate
     NameError:
       undefined local variable or method `config' for #<RSpec::Core::ExampleGroup::Nested_6:0x007ff61c721a68>
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-expectations-2.11.3/lib/rspec/matchers/method_missing.rb:9:in `method_missing'
     # ./spec/support/active_record/postgresql_setup.rb:35:in `active_record_gp_migrate'
     # ./spec/database_cleaner/active_record/truncation/postgresql_spec.rb:11:in `block (2 levels) in <module:ConnectionAdapters>'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:113:in `instance_eval'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:113:in `block in run'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:253:in `with_around_each_hooks'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/example.rb:110:in `run'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:378:in `block in run_examples'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:374:in `map'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:374:in `run_examples'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/example_group.rb:360:in `run'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/reporter.rb:34:in `report'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in `run'
     # /Users/VuTran/.rvm/gems/ruby-2.1.3/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `block in autorun'
```

**Comment by etagwerker** [comment]
Fixed, thanks!
