### ISSUE TITLE
DatabaseCleaner::Mongoid not loaded when strategy not existed

### ISSUE THREAD

**Issue by sikachu** [DatabaseCleaner/database_cleaner#36]
Hi,

I'm currently using the edge `database_cleaner` with edge `cucumber-rails` I've tried to run cucumber feature which defaults try to use `:transaction` strategy on my ORM, and it turns out that `DatabaseCleaner::Mongoid` doesn't get included on error.

Here is the trace log:

```
Using the default profile...
uninitialized constant DatabaseCleaner::Mongoid (NameError)
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/configuration.rb:72:in `orm_module'
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/base.rb:93:in `orm_module'
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/base.rb:100:in `rescue in orm_strategy'
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/base.rb:97:in `orm_strategy'
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/base.rb:33:in `create_strategy'
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/base.rb:47:in `strategy='
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/configuration.rb:30:in `block in strategy='
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/configuration.rb:30:in `each'
/Users/sikachu/.rvm/gems/ruby-1.9.2-p0@genesis/bundler/gems/database_cleaner-9bd76e743de3/lib/database_cleaner/configuration.rb:30:in `strategy='
/Users/sikachu/Projects/cucumber-rails/lib/cucumber/rails/hooks/database_cleaner.rb:5:in `<top (required)>'
/Users/sikachu/Projects/cucumber-rails/lib/cucumber/rails.rb:9:in `<top (required)>'
/Users/sikachu/Projects/genesis/features/support/env.rb:7:in `require'
/Users/sikachu/Projects/genesis/features/support/env.rb:7:in `<top (required)>'
```

I've dug into the source code and couldn't find the culprit. Would you mind helping me out for this? Thank you :)

**Comment by Sshobhit** [comment]
@ADogan this worked for me. Thanks
