### ISSUE TITLE
Mongoid 5.0.0beta Compatability?

### ISSUE THREAD

**Issue by sliuu** [DatabaseCleaner/database_cleaner#386]
Looks like database_cleaner is not compatible with the newest beta version of mongoid

```
undefined method `remove_all' for #<Mongo::Collection::View:0x00000006771220> (NoMethodError)
      /home/ubuntu/myapp/vendor/bundle/ruby/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/moped/truncation_base.rb:14:in `block in clean'
      /home/ubuntu/myapp/vendor/bundle/ruby/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/moped/truncation_base.rb:14:in `each'
      /home/ubuntu/myapp/vendor/bundle/ruby/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/moped/truncation_base.rb:14:in `clean'
      /home/ubuntu/myapp/vendor/bundle/ruby/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:86:in `clean'
      /home/ubuntu/myapp/vendor/bundle/ruby/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:79:in `block in clean'
      /home/ubuntu/myapp/vendor/bundle/ruby/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:79:in `each'
      /home/ubuntu/myapp/vendor/bundle/ruby/2.2.0/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:79:in `clean'
      /home/ubuntu/myapp/vendor/bundle/ruby/2.2.0/gems/cucumber-rails-1.4.2/lib/cucumber/rails/hooks/database_cleaner.rb:9:in `After'
```

**Comment by geerzo** [comment]
This is solved with #385
