### ISSUE TITLE
ActiveRecord 5.0 internal metadata table should not be cleaned

### ISSUE THREAD

**Issue by md5** [DatabaseCleaner/database_cleaner#445]
I'm building an app using Rails 5.0.0.rc1 and I ran into the fact that the `ar_internal_metadata` table is being cleaned with the `:truncation` strategy. This is similar to #317.

When this happens and `ActiveRecord::Migration.maintain_test_schema!` is being used, tests/specs will fail if there are pending migrations and `database_cleaner` has had a chance to run and clear the metadata table. The error looks like this:

```
$ bundle exec rspec
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

    bin/rails db:environment:set RAILS_ENV=test

/Users/mike/dev/my_app/bin/rails:9:in `require'
/Users/mike/dev/my_app/bin/rails:9:in `<top (required)>'
/Users/mike/dev/my_app/bin/spring:13:in `require'
/Users/mike/dev/my_app/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
Coverage report generated for RSpec to /Users/mike/dev/my_app/coverage. 29 / 547 LOC (5.3%) covered.
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:572:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

    bin/rails db:migrate RAILS_ENV=test

    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:585:in `load_schema_if_pending!'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:591:in `block in maintain_test_schema!'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:822:in `suppress_messages'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:596:in `method_missing'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:591:in `maintain_test_schema!'
    from /Users/mike/dev/my_app/spec/rails_helper.rb:32:in `<top (required)>'
    from /Users/mike/dev/my_app/spec/controllers/widgets_controller_spec.rb:2:in `require'
    from /Users/mike/dev/my_app/spec/controllers/widgets_controller_spec.rb:2:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1333:in `load'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1333:in `block in load_spec_files'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1331:in `each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1331:in `load_spec_files'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:106:in `setup'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:92:in `run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:78:in `run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:45:in `invoke'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/exe/rspec:4:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/bin/rspec:23:in `load'
    from /usr/local/var/rbenv/versions/2.3.1/bin/rspec:23:in `<main>'
```

As with was the case with #317, adding the table to the `except` list is a workaround:

``` ruby
DatabaseCleaner.clean_with :truncation, except: %w(public.ar_internal_metadata)
```

**Comment by awilkening** [comment]
@md5 Can I see an example of your rails_helper.rb? I am unable to get DatabaseCleaner to leave the ar_internal_metadata table in the db. I assume it's a difference in setup.

**Comment by awilkening** [comment]
@md5 I was able to figure it out. This particular app is not using psql and is using mysql. The following is the correct way to use with mysql.

`DatabaseCleaner.clean_with :truncation, except: %w(ar_internal_metadata)`

**Comment by roberts1000** [comment]
I'm running into this as well using Postgres 9.5, Rails 5.0.0.1 and DatabaseCleaner 1.5.3.  `DatabaseCleaner.clean_with :truncation, except: %w(ar_internal_metadata)` helps as a workaround.

I triggered the bug by doing the following:

1. Run `bundle exec rake db:drop db:create db:migrate RAILS_ENV=test`  to prepare for testing.
2. Run `bundle exec rspec` one time.  The test runs, but `ar_internal_metadata` gets corrupted.
3. Run `bundle exec rake db:drop db:create db:migrate  RAILS_ENV=test` and get the error referenced in the original post.  At this point, I have destroy the database in the `psql` console to recover.

Unfortunately, we're having a hard time repeating this bug in all environments.  I can run `bundle exec rspec` as many times as I want without having problems on my development machine.  A colleague of mine ran into this problem for a week and then it just "went away".  I finally ran into it when I was trying to configure a Jenkins job to run the steps I mentioned above.  It failed every time on the machine with Jenkins.

**Comment by duffyjp** [comment]
This has started happening to me on Jenkins.  I'm running with RSpec and Capybara, and use the appropriate RSpec config settings for that setup. (see below).  Everything *was* working fine, just started a week ago or so for no discernible reason.

Rails: 5.0.6
Database Cleaner: 1.6.2

Tests run for a moment then I get this:

```
..rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

        bin/rails db:environment:set RAILS_ENV=test

/home/jenkins/.rvm/gems/ruby-2.3.5/gems/activerecord-5.0.6/lib/active_record/migration.rb:1277:in `last_stored_environment'
/home/jenkins/.rvm/gems/ruby-2.3.5/gems/activerecord-5.0.6/lib/active_record/tasks/database_tasks.rb:48:in `check_protected_environments!'
/home/jenkins/.rvm/gems/ruby-2.3.5/gems/activerecord-5.0.6/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/home/jenkins/.rvm/gems/ruby-2.3.5/gems/activerecord-5.0.6/lib/active_record/railties/databases.rake:363:in `block (3 levels) in <top (required)>'
/home/jenkins/.rvm/gems/ruby-2.3.5/gems/railties-5.0.6/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/jenkins/.rvm/gems/ruby-2.3.5/gems/railties-5.0.6/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/jenkins/.rvm/gems/ruby-2.3.5/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/jenkins/.rvm/gems/ruby-2.3.5/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
```

Here is the DatabaseCleaner chunk of my `rails_helper.rb`

```ruby
  # https://github.com/DatabaseCleaner/database_cleaner#rspec-with-capybara-example
  config.use_transactional_fixtures = false
  config.before(:suite) { DatabaseCleaner.clean_with :truncation }
  config.before(:each)  { DatabaseCleaner.strategy = :transaction }
  config.before(:each, type: :feature) { DatabaseCleaner.strategy = :truncation }
  config.before(:each)  { DatabaseCleaner.start }
  config.after(:each)   { DatabaseCleaner.clean }
```

Confirmed the issue is erased ar_internal_metadata:

```
mysql> select * from ar_internal_metadata;
Empty set (0.00 sec)

mysql> 
```

I have tried the `except: %w(ar_internal_metadata)` workaround, but it had no effect.

**Comment by happycollision** [comment]
For what it's worth (and believe me, I have next to no idea what I am talking about), I think my problem with this was solved with `except: %w(ar_internal_metadata schema_migrations)`. I also was still getting the error after using `except: %w(ar_internal_metadata)` so I went hunting.

I added the `schema_migrations` part because I noticed that was a table that was originally in the DB after a successful reset. And it has the word "schema" in it. Just like the error message.

So...

¯\_(ツ)_/¯

**Comment by kaukas** [comment]
[This PR] only deals with PG but `ar_internal_metadata` is created for other RDBMSes, too. Any plans to support e.g. MySQL?

**Comment by gbirchmeier** [comment]
I'm running Rails 6, mysql, and cucumber-rails 1.8.0 gem, and seeing this annoying message whenever I run cucumber a second time.

This `except: %w(ar_internal_metadata)` workaround is not working for me (and neither is adding `schema_migrations` per @happycollision's comment).

**Comment by kevinhq** [comment]
> I'm running Rails 6, mysql, and cucumber-rails 2.0.0 gem, and seeing this annoying message whenever I run cucumber a second time.
> 
> This `except: %w(ar_internal_metadata)` workaround is not working for me (and neither is adding `schema_migrations` per @happycollision's comment).

Got exactly same problem.

**Comment by botandrose** [comment]
@gbirchmeier @kevinhq It sounds like you can reproduce this issue consistently! Can you reduce your app down to something you can share with me, so I figure out the issue and fix it?

**Comment by gbirchmeier** [comment]
@botandrose I can try to make some time for it.
