### ISSUE TITLE
Strange behaviour for multiple strategies (sequel + activerecord)

### ISSUE THREAD

**Issue by vbyno** [DatabaseCleaner/database_cleaner#467]
I'm getting an error on Jenkins environment:
```
Failure/Error: network_group = create(:network_group)
     ActiveRecord::StatementInvalid:
       Mysql2::Error: MySQL server has gone away: ROLLBACK TO SAVEPOINT active_record_1
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `query'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/savepoints.rb:13:in `exec_rollback_to_savepoint'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:272:in `rollback_to_savepoint'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_to_savepoint'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:118:in `rollback'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:179:in `rollback_transaction'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:186:in `rescue in within_new_transaction'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # /usr/local/rvm/gems/ruby-2.1.5@interface/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
```
It seems to be happen after incorrect transaction rollback performed by `database_cleaner`. (Maybe, it works incorrect if sequel transaction is included in ActiveRecord transaction?).

Here is my `database_cleaner` configuration:
```
RSpec.configure do |config|
    config.use_transactional_fixtures = false

    config.before(:suite) do
      DatabaseCleaner[:active_record].strategy = :transaction
      DatabaseCleaner[:sequel].strategy = :transaction
      DatabaseCleaner.clean_with :truncation
    end

    config.before(:each) do |example|
      DatabaseCleaner[:active_record].strategy = example.metadata[:js] ? :deletion : :transaction
      DatabaseCleaner.start unless example.metadata[:skip_cleaner]
    end

    config.after(:each) do |example|
      DatabaseCleaner.clean unless example.metadata[:skip_cleaner]
    end

    config.before(:all, truncate_before_all: true) do
      DatabaseCleaner.clean_with :truncation
    end
  end 
```
Sequel and AR use the same database:
```
test:
 adapter: mysql2
 encoding: utf8
 reconnect: true
 database: test_database
 pool: 50
 username: my_user
 password: my_password
 host: localhost
```
(mysql 5.6, database_cleaner 1.5.3, mysql2 0.3.14 and activerecord 4.2.7.1
Any thoughts what is might be caused by?

**Comment by etagwerker** [comment]
@vbyno Could you add more information about the scenario? 

Could you try setting up two connections to the database? One for Sequel and another for ActiveRecord? You can see how to configure database_cleaner over here: https://github.com/DatabaseCleaner/database_cleaner#how-to-use-with-multiple-orms

**Comment by vbyno** [comment]
@etagwerker , I've tried configuration like this, but had no luck.:
```
  RSpec.configure do |config|
    config.use_transactional_fixtures = false

    sequel_cleaner = DatabaseCleaner[:sequel, connection: *sequel_connection*]

    config.before(:each) do |example|
      sequel_cleaner.strategy = example.metadata[:js] ? :deletion : :transaction
      sequel_cleaner.start unless example.metadata[:skip_cleaner]
    end

    config.after(:each) { |example| sequel_cleaner.clean unless example.metadata[:skip_cleaner] }
    config.before(:suite) { sequel_cleaner.clean_with :truncation }


    active_record_cleaner = DatabaseCleaner[:active_record, connection: :default]

    config.before(:each) do |example|
      active_record_cleaner.strategy = example.metadata[:js] ? :truncation : :transaction
      active_record_cleaner.start unless example.metadata[:skip_cleaner]
    end

    config.after(:each) { |example| active_record_cleaner.clean unless example.metadata[:skip_cleaner] }
    config.before(:suite) { active_record_cleaner.clean_with :truncation }
  end```

There are a few tests that fail with such an exception. But if I comment out the current test, the next one fails. 
Also, there are some test failures that are fallen because of uncleaned DB data.
This happens on Jenkins. Tests are running for ~1 hour as usual.

**Comment by vbyno** [comment]
It looks like the issue is not reproducible within new `DatabaseCleaner` versions. I'll close it.
