### ISSUE TITLE
Transaction fails with Sequel

### ISSUE THREAD

**Issue by brauliobo** [DatabaseCleaner/database_cleaner#474]
```
NoMethodError: undefined method `pop' for nil:NilClass
  /home/braulio/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.3/lib/database_cleaner/sequel/transaction.rb:31:in `clean'
  /home/braulio/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:46:in `clean_with'
  /home/braulio/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:91:in `block in clean_with'
  /home/braulio/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:91:in `each'
  /home/braulio/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:91:in `clean_with'
  /home/braulio/Projects/olery/scheduler/spec/support/database_cleaner.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by kaikuchn** [comment]
I just ran into the same problem. In my case it's because `Sequel::DATABASES` was empty when calling `DatabaseCleaner.start`.

Thus I simply had to initialise the connection to my database before calling `DatabaseCleaner.start`
