### ISSUE TITLE
MySQL table_stats_query failed when table name is one of reserved words

### ISSUE THREAD

**Issue by u46esp** [DatabaseCleaner/database_cleaner#517]
First off - database_cleaner is such a great help for me! Kudos to all contributors for your efforts in building, polishing and maintaining this. 

I use MySQL for a Rails project which we use database_cleaner and RSpec to perform testing. Recently we've upgraded database_cleaner from version 1.5.0 to 1.6.2 and we can't clean with delete strategy anymore. We found out at some point that one of our tables is names __"references"__ and it's reserved word in MySQL. Following are error logs (project name/full database schema stripped down to demonstrate problems)

```
Randomized with seed 60081

An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean_with(:deletion)

ActiveRecord::StatementInvalid:
  Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'references' at line 1: SELECT "parameters" AS table_name, COUNT(*) AS exact_row_count FROM parameters UNION SELECT "references" AS table_name, COUNT(*) AS exact_row_count FROM references
# /apps/rvm/gems/ruby-2.4.1@project/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
# /apps/rvm/gems/ruby-2.4.1@project/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
# /apps/rvm/gems/ruby-2.4.1@project/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
# /apps/rvm/gems/ruby-2.4.1@project/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:223:in `execute_and_free'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `exec_query'
# /apps/rvm/gems/ruby-2.4.1@project/gems/database_cleaner-1.6.2/lib/database_cleaner/active_record/deletion.rb:59:in `tables_with_new_rows'
# /apps/rvm/gems/ruby-2.4.1@project/gems/database_cleaner-1.6.2/lib/database_cleaner/active_record/deletion.rb:49:in `tables_to_truncate'
# /apps/rvm/gems/ruby-2.4.1@project/gems/database_cleaner-1.6.2/lib/database_cleaner/active_record/deletion.rb:108:in `block in clean'
# /apps/rvm/gems/ruby-2.4.1@project/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:183:in `disable_referential_integrity'
# /apps/rvm/gems/ruby-2.4.1@project/gems/database_cleaner-1.6.2/lib/database_cleaner/active_record/deletion.rb:107:in `clean'
# /apps/rvm/gems/ruby-2.4.1@project/gems/database_cleaner-1.6.2/lib/database_cleaner/base.rb:46:in `clean_with'
# /apps/rvm/gems/ruby-2.4.1@project/gems/database_cleaner-1.6.2/lib/database_cleaner/configuration.rb:91:in `block in clean_with'
# /apps/rvm/gems/ruby-2.4.1@project/gems/database_cleaner-1.6.2/lib/database_cleaner/configuration.rb:91:in `each'
# /apps/rvm/gems/ruby-2.4.1@project/gems/database_cleaner-1.6.2/lib/database_cleaner/configuration.rb:91:in `clean_with'
# ./spec/rails_helper.rb:120:in `block (2 levels) in <top (required)>'
```

And following are my sort-of db/schema.rb
```
ActiveRecord::Schema.define(version: 20180101012342) do

  create_table "parameters", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci" do |t|
    t.string "key"
    t.text "value"
    t.string "description"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "references", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci" do |t|
    t.string "type"
    t.string "name"
    t.string "abbreviation"
    t.string "description", limit: 5000
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean "active_ind", default: true
  end
```

My Ruby-fu are not smart enough to do monkey patch the code but following modification (in https://github.com/DatabaseCleaner/database_cleaner/blob/master/lib/database_cleaner/active_record/deletion.rb#L70) allows me to get past the errors we got.  

```ruby
def table_stats_query(connection, db_name)
  if @cache_tables && !@table_stats_query.nil?
    return @table_stats_query
  else
    @table_stats_query = connection.select_values(<<-SQL).join(' UNION ')
           SELECT CONCAT('SELECT \"', table_name, '\" AS table_name, COUNT(*) AS exact_row_count FROM \`', table_name, '\`')
           FROM
           INFORMATION_SCHEMA.TABLES
           WHERE
           table_schema = '#{db_name}'
           AND #{::DatabaseCleaner::ActiveRecord::Base.exclusion_condition('table_name')};
    SQL
  end
end
```

I'm not sure that a) This problems also happens to other db adapters or not and b) this fix won't cause problems elsewhere as well.

Please advise.

**Comment by proton** [comment]
I think it's better to change ` (backquote) to " (doublequote)

**Comment by ahorek** [comment]
https://github.com/DatabaseCleaner/database_cleaner/pull/501

**Comment by mauro-oto** [comment]
Closed via https://github.com/DatabaseCleaner/database_cleaner/pull/501
