### ISSUE TITLE
Will next version be compatible with Ruby MongoDB driver 2.5+?

### ISSUE THREAD

**Issue by P9GIT** [DatabaseCleaner/database_cleaner#590]
Current version 1.7.0 is incompatible with Ruby MongoDB driver 2.5+ due to the addition of session pool from 2.5 and onward. 

I get an exception when attempting a "clean":  `TypeError: Time can't be coerced into Integer`

Back trace:
```
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/session/session_pool.rb:128:in `-'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/session/session_pool.rb:128:in `about_to_expire?'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/session/session_pool.rb:82:in `block (2 levels) in checkout'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/session/session_pool.rb:77:in `loop'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/session/session_pool.rb:77:in `block in checkout'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/session/session_pool.rb:76:in `synchronize'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/session/session_pool.rb:76:in `checkout'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/cluster.rb:511:in `get_session'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/client.rb:445:in `get_session'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/database/view.rb:55:in `collection_names'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/database.rb:117:in `collection_names'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/mongo-2.5.3/lib/mongo/database.rb:141:in `collections'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/forwardable.rb:230:in `collections'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/database_cleaner-1.7.0/lib/database_cleaner/mongo2/truncation_mixin.rb:29:in `collections'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/database_cleaner-1.7.0/lib/database_cleaner/mongo2/truncation_mixin.rb:9:in `clean'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/database_cleaner-1.7.0/lib/database_cleaner/base.rb:94:in `clean'
/var/www/portal/spec/support/helpers.rb:18:in `block (2 levels) in <module:Helpers>'
```

So my question is: will the next version be able to handle the 2.5+ Ruby MongoDB driver?

Thanks!
Thomas.

**Comment by FunkyloverOne** [comment]
@P9GIT that's strange, I'm using it with `mongo (2.9.0)` in my `Gemfile.lock` without any issues.
Here's my rspec config:
```ruby
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.clean_with :truncation
  end

  config.before(:each) do
    DatabaseCleaner.start
    ActionMailer::Base.deliveries.clear
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

# ...

end
```

**Comment by P9GIT** [comment]
Hi @FunkyloverOne 

I've digged further into this and it turns out that the bug was in the testing code, NOT in database cleaner.
Closing the issue.
