### ISSUE TITLE
require 'database_cleaner/active_record' fails with rails 4.2.11.1

### ISSUE THREAD

**Issue by kramuenke** [DatabaseCleaner/database_cleaner#623]
Hi,

we upgraded from 1.7.0 to 1.8.2 and now getting the following error when running specs

```
An error occurred while loading spec_helper.
Failure/Error: require 'database_cleaner/active_record'

ArgumentError:
  Delegation needs a target. Supply an options hash with a :to key as the last argument (e.g. delegate :hello, to: :greeter).
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/core_ext/module/delegation.rb:154:in `delegate'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner/base.rb:56:in `<class:Base>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner/base.rb:8:in `<module:DatabaseCleaner>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner/base.rb:7:in `<top (required)>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner/configuration.rb:1:in `<top (required)>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-1.8.2/lib/database_cleaner.rb:3:in `<top (required)>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/database_cleaner-active_record-1.8.0/lib/database_cleaner/active_record.rb:2:in `<top (required)>'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
# /Users/kairamuenke/.gem/ruby/2.5.7/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
# ./spec/spec_helper.rb:24:in `<top (required)>'

```

**Comment by etagwerker** [comment]
@kramuenke Could you share what your `Gemfile.lock` looks like? My first impression is that it's weird that you have both `database_cleaner-active_record-1.8.0` and `database_cleaner-active_record-1.8.2` in your app, but maybe that has nothing to do with it.

**Comment by kramuenke** [comment]
here is the diff after changing `Gemfile` and running `bundle install`

```
diff --git a/Gemfile b/Gemfile
index 6eaee6a381..0e8b807121 100644
--- a/Gemfile
+++ b/Gemfile
@@ -117,7 +117,7 @@ gem 'will_paginate', '~> 3'
 group :development, :cucumber, :test do
   gem 'awesome_print'
   gem 'compass-validator', require: false
-  gem 'database_cleaner', '~> 1.7.0', require: false
+  gem 'database_cleaner-active_record', require: false
   gem 'email_spec', require: false
   gem 'equivalent-xml'
   gem 'fakefs', require: false
diff --git a/Gemfile.lock b/Gemfile.lock
index fc4d069d15..2dae75c524 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -205,7 +205,10 @@ GEM
     cucumber-tag_expressions (1.1.1)
     cucumber-wire (0.0.1)
     dalli (1.1.5)
-    database_cleaner (1.7.0)
+    database_cleaner (1.8.2)
+    database_cleaner-active_record (1.8.0)
+      activerecord
+      database_cleaner (~> 1.8.0)
     dataloader (1.0.0)
       concurrent-ruby (~> 1)
       promise.rb (~> 0.7.3)
@@ -744,7 +747,7 @@ DEPENDENCIES
   compass-validator
   cucumber-rails
   dalli (~> 1)
-  database_cleaner (~> 1.7.0)
+  database_cleaner-active_record
   dataloader (~> 1)
   ddtrace (~> 0)
   delighted
```

**Comment by kramuenke** [comment]
i think we figured it out... looks like a load order problem and removing `require: false` avoids ActiveSupport tentacles to overload `delegate`

**Comment by botandrose** [comment]
Well, this is interesting. It sounds possible to get ActiveSupport to mess with our usage of `delegate`?? I'd like to prevent this from happening, if possible. I'm going to see if I can reproduce.

**Comment by botandrose** [comment]
@kramuenke If you can reduce this down to a gist or a repo that reproduces the failure, I'd be happy to fix it.

I tried to reproduce with the following, but failed:

```ruby
gem "activerecord", "~>4.2"
gem "database_cleaner-active_record", "~>1.8"

require "active_support"
require "database_cleaner/active_record"
```
