### ISSUE TITLE
edge rails (future 7.1) no longer has ActiveRecord::SchemaMigration.table_name

### ISSUE THREAD

**Issue by jrochkind** [DatabaseCleaner/database_cleaner#693]
Current edge rails (future Rails 7.1) produces an error from cleaning in `:truncation` or `:deletion` strategies, due to `ActiveRecord::SchemaMigration.table_name` apparently being removed. 

eg

```
Failure/Error: DatabaseCleaner.clean_with(:truncation)

       NoMethodError:
         undefined method `table_name' for ActiveRecord::SchemaMigration:Class
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/base.rb:73:in `migration_table_name'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/truncation.rb:271:in `migration_storage_names'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/lib/database_cleaner/generic/truncation.rb:14:in `initialize'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/adapters/database_cleaner-active_record/lib/database_cleaner/active_record/truncation.rb:238:in `initialize'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/lib/database_cleaner/base.rb:128:in `new'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/lib/database_cleaner/base.rb:128:in `create_strategy'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/lib/database_cleaner/base.rb:75:in `clean_with'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/lib/database_cleaner/configuration.rb:93:in `block in clean_with'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/lib/database_cleaner/configuration.rb:93:in `each'
       # /Users/jrochkind/.gem/ruby/3.0.4/gems/database_cleaner-1.99.0/lib/database_cleaner/configuration.rb:93:in `clean_with'```
```

It looks like this is the commit where it moved: https://github.com/rails/rails/commit/436277da88507f9aae0874e62f3e61a8546b9683

It looks like similar things have happened in the past that effected database_cleaner, eg https://github.com/DatabaseCleaner/database_cleaner/issues/476

**Comment by bdewater** [comment]
FWIW Rails 6 shipped with a `db:truncate_all` task, you can add in your test helper for the same effect ([docs](https://api.rubyonrails.org/classes/ActiveRecord/Tasks/DatabaseTasks.html#method-i-truncate_all)):
```ruby
after do
  ActiveRecord::Tasks::DatabaseTasks.truncate_all
end
```

**Comment by brian-kephart** [comment]
Looks like the source of the issue is a dependent gem, which now has an open PR. See https://github.com/DatabaseCleaner/database_cleaner-active_record/pull/78/commits/19327d190a8744a245b7ed031144eb7ef3dab28b

**Comment by sebaherrera07** [comment]
> Looks like the source of the issue is a dependent gem, which now has an open PR. See [DatabaseCleaner/database_cleaner-active_record@19327d1](https://github.com/DatabaseCleaner/database_cleaner-active_record/commit/19327d190a8744a245b7ed031144eb7ef3dab28b)

Nice. I saw the PR was opened in early December and didn't have any more activity, so I opened a new PR: https://github.com/DatabaseCleaner/database_cleaner-active_record/pull/80 . Hope it works and we can get this issue resolved 🙏
